name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY_REPO: ${{ secrets.KEY_REPO }}
      KEY_TOKEN: ${{ secrets.KEY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Android Keystore
        if: ${{ env.KEY_REPO != '' && env.KEY_TOKEN != '' }}
        uses: actions/checkout@v3
        with:
          repository: ${{ env.KEY_REPO }}
          token: ${{ env.KEY_TOKEN }}
          path: keystore
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build With Gradle
        run: |
          chmod +x gradlew
          ./gradlew :app:assembleAppRelease --build-cache --parallel --daemon --warning-mode all
          ./gradlew -Pfrpc :app:assembleFrpcRelease --build-cache --parallel --daemon --warning-mode all
      - name: Upload Artifact(app)
        uses: actions/upload-artifact@v3
        with:
          name: FQWeb
          path: ${{ github.workspace }}/app/build/outputs/apk/app/release/FQWeb*.apk
      - name: Upload Artifact(frpc-arm64)
        uses: actions/upload-artifact@v3
        with:
          name: FQWeb-frpc-arm64
          path: ${{ github.workspace }}/app/build/outputs/apk/frpc/release/FQWeb*arm64-v8a.apk
      - name: Upload Artifact(frpc-arm32)
        uses: actions/upload-artifact@v3
        with:
          name: FQWeb-frpc-arm32
          path: ${{ github.workspace }}/app/build/outputs/apk/frpc/release/FQWeb*armeabi-v7a.apk
      - name: Upload Artifact(frpc-armAll)
        uses: actions/upload-artifact@v3
        with:
          name: FQWeb-frpc-armAll
          path: ${{ github.workspace }}/app/build/outputs/apk/frpc/release/FQWeb*armAll.apk
